name: wts_customer
description: A new Flutter application.


  #............for sha1 release key....................
  #............for keyhash...................................
  # keytool -exportcert -alias key0 -keystore /Users/mdyousufbhuiyan/MyDrive/Flutter/tanvir /wts-engineer/wts-engineer/android/Keystore/wts_support_engineer.jks | openssl sha1 -binary | openssl base64
  #............for sha1 release key....................

  #............for sha1 release key....................
  #.......firstway........and workable way..............
  #....go to andorid folder and run
  #..............(./gradlew signingReport)
  #..............another way...............
# keytool -list -v -keystore /Users/mdyousufbhuiyan/MyDrive/Flutter/tanvir /wts-engineer/wts-engineer/android/Keystore/wts_support_engineer.jks -alias key0




# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#................after update version code ,need to run flutter build apk.............
version: 1.1.5+11

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.11

  transparent_image: ^2.0.1
  flutter_spinkit: ^5.2.0
  get: ^4.6.6
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  fluttertoast: ^8.2.2

  firebase_messaging: ^14.6.8
  firebase_core: ^2.16.0
  firebase_analytics: ^10.5.0
  firebase_crashlytics: ^3.3.6
  firebase_auth: ^4.10.0

  #  firebase_auth: ^0.18.1+2
  cloud_firestore: ^4.9.2
  #    # ...........................fcm source...........................
  #    #https://github.com/Amanullahgit/FCM_Flutter-Notification
  flutter_local_notifications: ^15.1.1
  #  flutter_local_notifications: ^3.0.1+7
  #  firebase_storage: ^4.0.1
  animated_text_kit: ^4.2.2
  auto_size_text: ^3.0.0
  http: ^1.1.0
  #....................retrofit.................
  retrofit: ^4.0.1
  dio: ^5.3.2
  built_value: any
  json_annotation: any
  logger: ^2.0.2
  built_value_generator: any
  #.................network image........
  cached_network_image: ^3.2.3
  loading_overlay: ^0.3.0
  shared_preferences: ^2.2.1
  intl: ^0.18.1
  # chopper.........
  chopper: ^7.0.6

  # Remote API
  connectivity: ^3.0.6
  # Remote API
  #data_connection_checker: ^0.3.4
  internet_connection_checker: ^1.0.0+1
  #flutter_swiper: ^1.1.6
  flutter_swiper_view: ^1.1.8
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.5.0
  #flutter_search_bar: ^2.1.0
  easy_search_bar: ^2.5.0
  path_provider: ^2.1.1
  #modal_bottom_sheet: ^2.1.2
  modal_bottom_sheet: ^3.0.0-pre
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.14
  hexcolor: ^3.0.1
    # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  #....................chopper.................
  build_runner: any
  json_serializable: any
  mockito: ^5.4.2
  chopper_generator: ^7.0.4
  #flutter_launcher_icons: "^0.9.0"

dependency_overrides:
  analyzer: ^6.2.0



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/login_screen_logo.png
  #generate: true
  #command: flutter pub run flutter_launcher_icons:main
#flutter_icons:
#  image_path: "assets/launcher.png"
#  android: true
#  ios: true
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
